{ ... }:
{
  flake.nixosModules.emacs =
    { pkgs, config, ... }:
    let
      colors = config.lib.stylix.colors.withHashtag;
    in
    {
      home-manager.users.jeffrey = {
        stylix.targets.emacs.enable = false;

        home.file.".config/doom/stylix-colors.el".text = ''
          ;;; stylix-colors.el --- Generated by Nix -*- lexical-binding: t; -*-
          (defvar stylix-base00 "${colors.base00}")
          (defvar stylix-base01 "${colors.base01}")
          (defvar stylix-base02 "${colors.base02}")
          (provide 'stylix-colors)
        '';

        programs.emacs = {
          enable = true;
          package = pkgs.emacs-pgtk;
          extraPackages =
            epkgs: with epkgs; [
              vterm
            ];
        };

        home.packages = with pkgs; [
          cmake
          gcc
          libtool
          gnumake
          binutils
          gnutls
          imagemagick
          zstd
          editorconfig-core-c
          sqlite
          vips
          ffmpegthumbnailer
          mediainfo
          p7zip
          texlive.combined.scheme-full
          (aspellWithDicts (
            ds: with ds; [
              en
              nl
            ]
          ))
          nodejs
          typescript-language-server
          vscode-langservers-extracted
          clang-tools
          ruff
          pyright
          texlab
          nixd
          nil
          tree-sitter
          shellcheck
          statix
        ];

        home.sessionPath = [
          "$HOME/.config/emacs/bin"
        ];

        xdg.desktopEntries."emacsclient" = {
          name = "Emacs (Client)";
          noDisplay = true;
        };
        xdg.desktopEntries."emacsclient-mail" = {
          name = "Emacs (Client) Mail";
          noDisplay = true;
        };
        xdg.desktopEntries."emacs-mail" = {
          name = "Emacs Mail";
          noDisplay = true;
        };

      };
    };
}
