{ ... }:
{
  flake.nixosModules.emacs =
    { pkgs, config, ... }:
    let
      colors = config.lib.stylix.colors.withHashtag;
    in
    {
      home-manager.users.jeffrey = {
        stylix.targets.emacs.enable = false;

        home.file.".config/doom/stylix-colors.el".text = ''
          ;;; stylix-colors.el --- Generated by Nix -*- lexical-binding: t; -*-
          (defvar stylix-base00 "${colors.base00}")
          (defvar stylix-base01 "${colors.base01}")
          (defvar stylix-base02 "${colors.base02}")
          (provide 'stylix-colors)
        '';

        programs.emacs = {
          enable = true;
          package = pkgs.emacs-pgtk;
          extraPackages =
            epkgs: with epkgs; [
              vterm
              treesit-grammars.with-all-grammars
            ];
        };

        # Doom Emacs dependencies (LSPs and common tools are in packages.nix)
        home.packages = with pkgs; [
          cmake
          libtool
          gnumake
          binutils
          gnutls
          imagemagick
          zstd
          editorconfig-core-c
          sqlite
          texlive.combined.scheme-full
          (aspellWithDicts (
            ds: with ds; [
              en
              nl
            ]
          ))
        ];

        home.sessionPath = [
          "$HOME/.config/emacs/bin"
          "$HOME/.local/bin"
        ];
      };
    };
}
